export const articles={ko:[
{slug:"exam-overview",category:"시험 구조",title:"미용사(일반) 필기·실기 구조 한눈에 보기",description:"60문항 필기와 약 2시간 25분 작업형 실기를 분리해 준비합니다.",sections:[["필기는 60문항·60분입니다","객관식 4지 택일형으로 미용이론, 위생, 화장품과 헤어 실무 판단을 확인합니다."],["실기는 미용실무 작업형입니다","Q-Net은 약 2시간 25분의 작업형으로 안내하며 현재 과제와 준비물 공지를 시험 전에 확인해야 합니다."],["각 단계는 60점 이상입니다","필기와 실기는 각각 100점 만점에 60점 이상이어야 합니다."],["2026년과 2027년 기준을 구분합니다","현재 2022~2026 출제기준을 따르되 다음 연도 응시자는 2027~2031 기준 전환을 다시 확인하세요."]]},
{slug:"written-plan",category:"필기 전략",title:"60분 필기를 모발·위생·시술로 묶어 공부하기",description:"단편 암기를 고객 상태와 시술 선택의 흐름으로 바꿉니다.",sections:[["모발과 두피를 먼저 진단합니다","구조, 성장주기, 손상과 두피 상태를 시술 전 판단의 출발점으로 둡니다."],["위생은 모든 시술에 연결합니다","손, 도구, 린넨, 작업장과 고객 보호 원칙을 샴푸·커트·펌·컬러에 반복 적용합니다."],["화장품은 기능과 주의사항으로 정리합니다","성분명을 외우는 데 그치지 말고 사용 목적, 적용 순서와 안전상 주의를 연결합니다."],["60분 모의고사를 반복합니다","오답을 모발·위생·제품·시술로 나누고 같은 판단 실수를 묶어 복습합니다."]]},
{slug:"hair-scalp",category:"모발·두피",title:"모발과 두피 상태를 시술 판단으로 연결하기",description:"구조와 손상 원인을 관찰 가능한 상태와 관리 선택으로 바꿉니다.",sections:[["모발 구조를 기능으로 봅니다","큐티클, 코텍스와 메듈라가 물리적·화학적 시술에 어떻게 반응하는지 연결합니다."],["두피 상태를 구분합니다","건성·지성·민감 상태의 관찰 포인트와 피해야 할 자극을 비교합니다."],["손상 원인을 추적합니다","열, 마찰, 자외선, 화학 시술이 겹쳤을 때 탄력과 다공성이 어떻게 달라지는지 봅니다."],["진단에서 시술로 이어갑니다","고객 상태에 따라 제품, 열, 장력과 처리시간을 보수적으로 조정하는 판단을 연습합니다."]]},
{slug:"hygiene-safety",category:"위생·안전",title:"도구 소독과 고객 보호를 작업 루틴으로 만들기",description:"위생 지식을 매 시술 전후에 반복되는 행동으로 고정합니다.",sections:[["청소·소독·멸균을 구분합니다","대상과 오염 수준에 맞는 처리 목적과 방법을 구분합니다."],["접촉면과 린넨을 관리합니다","피부·두피에 닿는 도구, 타월, 케이프와 작업대의 교체·보관 순서를 정합니다."],["고객 보호를 먼저 배치합니다","상태 확인, 보호구, 약제 접촉 방지와 이상 반응 대응을 시술 전에 준비합니다."],["작업 후 순환을 끝냅니다","폐기물 분리, 도구 세척·소독, 건조와 다음 고객용 세팅까지 한 사이클로 봅니다."]]},
{slug:"shampoo-scalp-care",category:"샴푸",title:"두피 스케일링과 백샴푸 순서 익히기",description:"고객 보호, 물 온도, 손동작과 헹굼을 끊기지 않는 흐름으로 연습합니다.",sections:[["준비와 보호부터 확인합니다","모델 조건, 케이프와 타월, 물 온도, 제품과 도구 배치를 먼저 확인합니다."],["구역과 순서를 고정합니다","두피를 빠짐없이 다루도록 구획을 정하고 압력과 손톱 접촉을 조절합니다."],["제품 잔여물을 남기지 않습니다","샴푸와 트리트먼트 목적에 맞춰 충분히 헹구고 얼굴과 의복을 보호합니다."],["마무리 상태를 점검합니다","두피 자극, 젖은 타월, 바닥 물기와 사용 도구를 즉시 정리합니다."]]},
{slug:"haircut",category:"커트",title:"커트를 섹션·각도·가이드로 구조화하기",description:"형태를 감으로 만들지 않고 기준선과 장력의 반복으로 완성합니다.",sections:[["최종 형태를 먼저 읽습니다","무게선, 층, 길이와 좌우 균형을 예상하고 섹션 계획을 세웁니다."],["가이드를 잃지 않습니다","고정·이동 가이드와 다음 패널의 연결을 매 절단마다 확인합니다."],["각도와 장력을 일정하게 유지합니다","머리 위치, 손가락 각도, 빗질과 모발 수분이 길이에 미치는 영향을 통제합니다."],["교차검사로 마무리합니다","다른 방향으로 빗어 길이와 연결을 확인하고 필요한 부분만 최소 수정합니다."]]},
{slug:"permanent-wave",category:"퍼머넌트",title:"와인딩을 블로킹·텐션·배열로 나눠 연습하기",description:"로드 선택과 일정한 장력으로 정확도와 시간 관리를 함께 높입니다.",sections:[["블로킹을 먼저 완성합니다","과제 도면과 두상 기준점에 맞춰 섹션의 크기와 경계를 분명히 합니다."],["패널 크기를 로드에 맞춥니다","너비와 두께가 로드 크기를 벗어나지 않도록 균일하게 분배합니다."],["텐션과 엔드페이퍼를 일정하게 합니다","모발 끝 꺾임과 느슨함을 막고 고무 밴드 압박을 조절합니다."],["배열과 시간도 평가합니다","방향, 간격, 고정 상태와 전체 완성 시간을 함께 기록합니다."]]},
{slug:"hair-color",category:"컬러",title:"색의 혼합과 도포를 안전하게 계획하기",description:"색상 원리, 구획, 도포량과 고객 보호를 한 작업표로 정리합니다.",sections:[["색상 관계를 먼저 봅니다","기본색, 보색과 혼합 결과를 예상하고 목표 색을 만드는 비율을 기록합니다."],["구획과 도포 순서를 정합니다","작업 범위를 명확히 나누고 누락과 경계 오염을 줄이는 방향으로 진행합니다."],["제품과 피부를 분리합니다","정해진 제품 상태를 유지하고 피부·의복·작업대를 보호합니다."],["결과를 깨끗하게 제출합니다","색의 균일성, 형태, 도구 정리와 주변 오염을 마지막에 확인합니다."]]},
{slug:"practical-day",category:"실기 전략",title:"약 145분 실기를 구간별로 운영하는 법",description:"준비, 샴푸, 커트, 와인딩과 컬러 작업을 시간표와 체크리스트로 관리합니다.",sections:[["공식 과제와 준비물을 최신 확인합니다","과거 영상보다 Q-Net의 현행 과제, 모델 조건과 지참준비물을 우선합니다."],["구간별 종료 시각을 정합니다","한 작업이 늦어져 나머지 전체가 무너지지 않도록 중간 마감 시간을 둡니다."],["정리는 다음 작업의 준비입니다","사용 도구와 폐기물을 즉시 치워 다음 구간의 작업 공간을 확보합니다."],["감점 위험을 먼저 점검합니다","고객 보호, 위생, 안전, 과제 규격과 미완성 위험을 미세한 미관 수정 전에 확인합니다."]]},
{slug:"six-week-plan",category:"학습 계획",title:"6주 필기·실기 연결 계획",description:"필기 개념을 도구 사용과 반복 작업으로 전환하는 일정을 만듭니다.",sections:[["1주는 구조와 진단입니다","60분 필기 모의고사와 실기 전 과정을 기록해 지식·속도·정확도 약점을 나눕니다."],["2~3주는 핵심 기술 분해입니다","샴푸, 커트, 와인딩과 컬러를 짧은 구간으로 나눠 자세와 순서를 교정합니다."],["4~5주는 연결 실습입니다","제한시간을 두고 여러 작업을 연속 수행하며 위생과 정리를 함께 채점합니다."],["6주는 시험 흐름을 재현합니다","준비물 점검부터 제출까지 실전처럼 반복하고 자주 생기는 감점 요인만 압축 복습합니다."]]}
],en:[
{slug:"exam-overview",category:"Format",title:"Korean Hairdresser exam at a glance",description:"Prepare separately for the 60-item written test and roughly 145-minute practical.",sections:[["Written: 60 items in 60 minutes","The four-option test covers hair theory, hygiene, cosmetics and salon decisions."],["Practical: hairdressing work","Q-Net describes an approximately 2-hour-25-minute task exam. Recheck current tasks and required materials."],["Each stage requires 60","Written and practical are each scored out of 100 with a pass mark of 60."],["Separate 2026 from the next standard","The current 2022–2026 specification is ending; 2027 candidates must verify the 2027–2031 transition."]]},
{slug:"written-plan",category:"Written strategy",title:"Group the written test by hair, hygiene and service",description:"Turn isolated facts into client-state and treatment decisions.",sections:[["Start with hair and scalp diagnosis","Use structure, growth, damage and scalp state as the basis for decisions."],["Apply hygiene everywhere","Repeat tool, linen, workplace and client-protection rules across services."],["Study cosmetics by function","Link purpose and order with safety cautions rather than memorising names alone."],["Run 60-minute mocks","Classify misses as hair, hygiene, product or service decisions."]]},
{slug:"hair-scalp",category:"Hair and scalp",title:"Connect hair and scalp condition to service choices",description:"Turn structure and damage causes into observable signs and safer choices.",sections:[["Read structure by function","Relate cuticle and cortex behaviour to physical and chemical work."],["Distinguish scalp states","Compare dry, oily and sensitive observations and avoidable irritation."],["Trace overlapping damage","Consider heat, friction, UV and chemical services together."],["Adjust the service","Use conservative product, heat, tension and processing choices when condition requires it."]]},
{slug:"hygiene-safety",category:"Hygiene and safety",title:"Make disinfection and client protection routine",description:"Fix hygiene knowledge into actions repeated before and after every service.",sections:[["Separate cleaning and disinfection","Choose a treatment purpose that fits the item and contamination."],["Manage contact surfaces and linen","Set replacement, storage and handling rules for tools, towels and capes."],["Protect the client first","Prepare condition checks, barriers and abnormal-reaction response."],["Finish the cycle","Handle waste, clean and disinfect tools, dry them and reset the station."]]},
{slug:"shampoo-scalp-care",category:"Shampoo",title:"Practise scalp care and back-shampoo order",description:"Connect protection, water, hand movement and rinsing without gaps.",sections:[["Prepare protection","Check the model, cape, towels, water, products and tool placement."],["Use fixed zones","Cover the scalp without nail contact or uncontrolled pressure."],["Remove residue","Rinse fully while protecting the face and clothing."],["Close cleanly","Check irritation, wet linen, floor water and used tools."]]},
{slug:"haircut",category:"Haircut",title:"Structure a cut with sections, angle and guide",description:"Build shape through repeatable references rather than guesswork.",sections:[["Read the target shape","Plan weight, layers, length and balance."],["Keep the guide","Track fixed or travelling references through every panel."],["Hold angle and tension","Control head position, fingers, combing and moisture."],["Cross-check","Comb in another direction and correct only what is necessary."]]},
{slug:"permanent-wave",category:"Permanent wave",title:"Split winding into blocking, tension and layout",description:"Improve accuracy and time through consistent rods and tension.",sections:[["Complete blocking first","Use task geometry and head landmarks."],["Match panel to rod","Keep width and thickness within the rod size."],["Control tension and papers","Prevent loose ends, fishhooks and band pressure."],["Score layout and time","Record direction, gaps, security and total completion time."]]},
{slug:"hair-color",category:"Hair colour",title:"Plan colour mixing and application safely",description:"Combine colour theory, zoning, amount and client protection.",sections:[["Predict the mix","Use primary and complementary relationships to target a result."],["Set zones and direction","Reduce gaps and boundary stains with a clear sequence."],["Separate product from skin","Protect skin, clothing and the workstation."],["Submit a clean result","Check uniformity, form, tools and surrounding stains."]]},
{slug:"practical-day",category:"Practical strategy",title:"Run the roughly 145-minute practical in sections",description:"Manage preparation, shampoo, cutting, winding and colour with checkpoints.",sections:[["Verify current tasks and materials","Prioritise Q-Net notices over old videos."],["Set section deadlines","Prevent one late task from consuming the full exam."],["Treat cleanup as setup","Clear tools and waste to prepare the next stage."],["Check deduction risks first","Review protection, hygiene, safety, specifications and incomplete work before cosmetic tweaks."]]},
{slug:"six-week-plan",category:"Study plan",title:"A six-week written-to-practical plan",description:"Convert theory into tool handling and repeated salon work.",sections:[["Week 1: diagnose","Run a timed written mock and record the full practical."],["Weeks 2–3: isolate techniques","Break shampoo, cutting, winding and colour into short corrections."],["Weeks 4–5: connect tasks","Run timed sequences while scoring hygiene and cleanup."],["Week 6: reproduce the exam","Repeat materials-to-submission and review recurring deductions."]]}
]};
